name: Update FLS
on:
  schedule:
    - cron: "05 0 * * *"
  workflow_dispatch:
jobs:
    update-fls:
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v4
        - name: Update FLS
          run: "./make.py --update-spec-lock-file"
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v4
          with:
            commit-message: Cloud - Update available list
            title: Update FLS (automated PR)
            body: Update FLS (automated PR)
            base: main
            labels: automated-pr
            branch: update-fls
            delete-branch: true
